name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check test status
        uses: actions/github-script@v7
        with:
          script: |
            const { data: checkRuns } = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.release.tag_name
            });

            const testRun = checkRuns.check_runs.find(run => run.name === 'test');

            if (!testRun) {
              core.setFailed('Test workflow not found for this release');
              return;
            }

            if (testRun.conclusion !== 'success') {
              core.setFailed(`Tests failed with status: ${testRun.conclusion}`);
              return;
            }

            core.info('Tests passed successfully');

      - name: Release application
        run: echo "Application released"
